- hosts: all
  become: yes
  tasks:
  - name: Set hostname from inventory
    hostname:
     name: "{{ inventory_hostname }}"
  vars:
    ansible_user: [insert_Linux_standard_user_account_that_is_used_in_cloud-init/user-data.yaml]

# Import kubespray playbook to deploy k8s cluster
- import_playbook: ./kubespray/cluster.yml
